from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.units import inch

def generate_hld():
    file_path = "Mithila_Gold_HLD.pdf"
    doc = SimpleDocTemplate(file_path, pagesize=A4)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Title'],
        fontSize=24,
        textColor=colors.HexColor("#B8860B"),  # Gold color
        spaceAfter=30
    )
    
    heading_style = ParagraphStyle(
        'HeadingStyle',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor("#8B0000"),  # Dark Red
        spaceBefore=20,
        spaceAfter=10
    )
    
    body_style = styles['BodyText']
    
    content = []

    # Title
    content.append(Paragraph("High-Level Design (HLD)", title_style))
    content.append(Paragraph("Project: Mithila Gold (E-commerce & POS)", styles['Normal']))
    content.append(Spacer(1, 0.5 * inch))

    # 1. Introduction
    content.append(Paragraph("1. System Overview", heading_style))
    content.append(Paragraph(
        "Mithila Gold is a dual-purpose platform serving both as a public e-commerce store and a "
        "Point-of-Sale (POS) system for physical shop management. It integrates automated "
        "document generation for professional billing and follows a modular agent-based architecture.",
        body_style
    ))

    # 2. Key Components
    content.append(Paragraph("2. System Components", heading_style))
    
    data = [
        ["Agent Name", "Primary Responsibility"],
        ["Public Store", "Catalog browsing, filtering, and cart management."],
        ["Farmer Identity", "User auth, session security, and farmer profiles."],
        ["Order Fulfillment", "Online order tracking and status management."],
        ["Point-of-Sale (POS)", "Manual admin sales for walk-in customers."],
        ["Document Generation", "ReportLab-based PDF receipt/invoice generation."],
        ["Global Config", "Centralized site settings and contact management."]
    ]
    
    t = Table(data, colWidths=[1.5 * inch, 4 * inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#B8860B")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    content.append(t)

    # 3. Data Architecture
    content.append(Paragraph("3. Technical Stack", heading_style))
    stack_text = (
        "<b>Backend:</b> Django 4.2 (Python)<br/>"
        "<b>Database:</b> PostgreSQL (Neon)<br/>"
        "<b>Frontend:</b> Vanilla CSS, HTML5, JavaScript<br/>"
        "<b>PDF Engine:</b> ReportLab<br/>"
        "<b>Static/Media:</b> WhiteNoise & Pillow<br/>"
        "<b>Deployment:</b> Fly.io / Render / Vercel"
    )
    content.append(Paragraph(stack_text, body_style))

    # 4. Workflow
    content.append(Paragraph("4. Operational Workflow", heading_style))
    workflow_text = (
        "1. Customers browse products through the <b>Public Store Agent</b>.<br/>"
        "2. Orders are processed by the <b>Order Fulfillment Agent</b>.<br/>"
        "3. Admins record walk-in sales via the <b>POS Agent</b>.<br/>"
        "4. Both flows trigger the <b>Document Generation Agent</b> to produce PDF receipts.<br/>"
        "5. The <b>Global Configuration Agent</b> ensures consistent branding across all touchpoints."
    )
    content.append(Paragraph(workflow_text, body_style))

    # Footer
    content.append(Spacer(1, 1 * inch))
    content.append(Paragraph("Generated by Mithila Gold System Agent", styles['Italic']))

    # Build PDF
    doc.build(content)
    print(f"PDF generated: {file_path}")

if __name__ == "__main__":
    generate_hld()
